version: '3.8'

services:
  xdb-server:
    image: xdblab/xdb-server:latest
    environment:
      CONFIG_PATH: /xdb/config/development-postgres.yaml
    ports:
      - "8801:8801"
      - "8701:8701"
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: "/xdb/script/install-schema-and-start-server.sh"
    network_mode: host # use host mode so that the 127.0.0.1 can point to Postgres
    # host network also make it possible for async service callback(otherwise it requires to set env AUTO_FIX_LOCALHOST_WORKER_URL=hostURL
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: xdb
      POSTGRES_PASSWORD: xdbxdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d xdb -U xdb"]
      interval: 3s
      timeout: 5s
      retries: 10
    networks:
      - xdb  
networks:
  xdb:
    driver: bridge