version: '3.8'

services:
  xcherry-server:
    image: xcherryio/xcherry-server:latest
    environment:
      CONFIG_PATH: /xcherry/config/development-postgres-docker-compose.yaml
      AUTO_FIX_LOCALHOST_WORKER_URL: host.docker.internal # this will let xcherry-server automatically replace all workerURL of "localhost" or "127.0.0.1" with "host.docker.internal"
#    volumes: # uncomment this to mount the local config/script for override 
#      - ../config:/xcherry/config
#      - ../script:/xcherry/script
    ports:
      - "8801:8801"
      - "8701:8701"
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: "/xcherry/script/install-schema-and-start-server-docker-compose.sh"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - xcherry
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: xcherry
      POSTGRES_PASSWORD: xcherryio
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d xcherry -U xcherry"]
      interval: 3s
      timeout: 5s
      retries: 10
    networks:
      - xcherry
networks:
  xcherry:
    driver: bridge