version: '3.8'

services:
  xdb-server:
    image: xdblab/xdb-server:latest
    environment:
      CONFIG_PATH: /xdb/config/development-postgres-docker-compose.yaml
      AUTO_FIX_LOCALHOST_WORKER_URL: host.docker.internal # this will let xdb-server automatically replace all workerURL of "localhost" or "127.0.0.1" with "host.docker.internal"
#    volumes: # uncomment this to mount the local config/script for override 
#      - ../config:/xdb/config
#      - ../script:/xdb/script
    ports:
      - "8801:8801"
      - "8701:8701"
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: "/xdb/script/install-schema-and-start-server-docker-compose.sh"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - xdb
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: xdb
      POSTGRES_PASSWORD: xdbxdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d xdb -U xdb"]
      interval: 3s
      timeout: 5s
      retries: 10
    networks:
      - xdb  
networks:
  xdb:
    driver: bridge