version: '3.8'

services:
  xcherry-server:
    image: xcherryio/xcherry-server:latest
    environment:
      CONFIG_PATH: /xcherry/config/development-postgres.yaml
    #volumes:
    #  - ../config:/xcherry/config # uncomment this to map to local config folder, so that you can modify the config directly for database username/password/etc
    network_mode: host # use host mode so that you can connect to your local database outside of this docker-compose
    # host network also make it possible for async service callback(otherwise it requires to set env AUTO_FIX_LOCALHOST_WORKER_URL=hostURL