log:
  stdout: true
  level: debug
  levelKey: "level"
database:
  processStore:
    dbExtensionName: postgres
    user: xcherry
    password: xcherryio
    databaseName: xcherry
    connectAddr: 127.0.0.1:5432
  visibilityStore:
    dbExtensionName: postgres
    user: xcherry
    password: xcherryio
    databaseName: xcherry
    connectAddr: 127.0.0.1:5432
asyncService:
  mode: cluster
  internalHttpServer:
    address: 0.0.0.0:8701
  membership:
    # replace the advertiseAddress with a real address
    advertiseAddress: 0.0.0.0:8901
    # this async server will be the first one to start and provide its address for others to join
    advertiseAddressToJoin: ""