log:
  stdout: true
  level: info
  levelKey: "level"
apiService:
  address: 0.0.0.0:8801
  defaultPollingMaxWaitSeconds: 60
database:
  sql:
    dbExtensionName: postgres
    user: xdb
    password: xdbxdb
    databaseName: xdb
    connectAddr: 127.0.0.1:5432
  