log:
  stdout: true
  level: debug
  levelKey: "level"
database:
  shards: 30
  processStore:
    dbExtensionName: postgres
    user: xcherry
    password: xcherryio
    databaseName: xcherry
    connectAddr: 127.0.0.1:5432
  visibilityStore:
    dbExtensionName: postgres
    user: xcherry
    password: xcherryio
    databaseName: xcherry
    connectAddr: 127.0.0.1:5432
asyncService:
  mode: cluster
  internalHttpServer:
    address: 0.0.0.0:8703
membership:
  bindAddress: 0.0.0.0:8903
  advertiseAddress: 0.0.0.0:8903
  advertiseAddressToJoin: 0.0.0.0:8888