log:
  stdout: true
  level: debug
  levelKey: "level"
database:
  shards: 30
  processStore:
    dbExtensionName: postgres
    user: xcherry
    password: xcherryio
    databaseName: xcherry
    connectAddr: 127.0.0.1:5432
  visibilityStore:
    dbExtensionName: postgres
    user: xcherry
    password: xcherryio
    databaseName: xcherry
    connectAddr: 127.0.0.1:5432
apiService:
  httpServer: # see more config fields in config.go
    address: 0.0.0.0:8801
    readTimeout: 10s
    writeTimeout: 60s
  asyncServiceAddresses:
    - 0.0.0.0:8701
    - 0.0.0.0:8702
    - 0.0.0.0:8703