log:
  stdout: true
  level: debug
  levelKey: "level"
apiService:
  httpServer: # see more config fields in config.go
     address: 0.0.0.0:8801
     readTimeout: 10s
     writeTimeout: 60s
database:
  processStore:
    dbExtensionName: postgres
    user: xcherry
    password: xcherryio
    databaseName: xcherry
    connectAddr: 127.0.0.1:5432
  visibilityStore:
    dbExtensionName: postgres
    user: xcherry
    password: xcherryio
    databaseName: xcherry
    connectAddr: 127.0.0.1:5432
asyncService:
  mode: consistent-hashing-cluster
  shard: 30
  internalHttpServer:
    clusterAddresses: 0.0.0.0:8701,0.0.0.0:8702,0.0.0.0:8703
    clusterAdvertiseAddresses: 0.0.0.0:8901,0.0.0.0:8902,0.0.0.0:8903