log:
  stdout: true
  level: debug
  levelKey: "level"
database:
  processStore:
    dbExtensionName: postgres
    user: xcherry
    password: xcherryio
    databaseName: xcherry
    connectAddr: 127.0.0.1:5432
  visibilityStore:
    dbExtensionName: postgres
    user: xcherry
    password: xcherryio
    databaseName: xcherry
    connectAddr: 127.0.0.1:5432
asyncService:
  mode: cluster
  internalHttpServer:
    address: 0.0.0.0:8702
  membership:
    # replace the following addresses with real addresses
    advertiseAddress: 0.0.0.0:8902
    advertiseAddressToJoin: 0.0.0.0:8901