log:
  stdout: true
  level: debug
  levelKey: "level"
database:
  shards: 30
  processStore:
    dbExtensionName: postgres
    user: xcherry
    password: xcherryio
    databaseName: xcherry
    connectAddr: 127.0.0.1:5432
  visibilityStore:
    dbExtensionName: postgres
    user: xcherry
    password: xcherryio
    databaseName: xcherry
    connectAddr: 127.0.0.1:5432
apiService:
  httpServer: # see more config fields in config.go
    address: 0.0.0.0:8801
    readTimeout: 10s
    writeTimeout: 60s
# Note: delete api server membership config if running async server in standalone mode
membership:
  bindAddress: 0.0.0.0:8888
  # replace the advertiseAddress with a real address
  advertiseAddress: 0.0.0.0:8888
  # this async server will be the first one to start and provide its address for others to join
  advertiseAddressToJoin: ""