log:
  stdout: true
  level: debug
  levelKey: "level"
apiService:
  httpServer: # see more config fields in config.go
     address: 0.0.0.0:8801
     readTimeout: 10s
     writeTimeout: 60s
  asyncServiceAddress: 0.0.0.0:8701
database:
  sql:
    dbExtensionName: postgres
    user: xcherry
    password: xcherryio
    databaseName: xcherry
    connectAddr: postgres:5432
asyncService:
  mode: standalone
  internalHttpServer:
    address: 0.0.0.0:8701