version: '3.8'

# Note this is to contain all dependencies to run for integ tests locally
include:
  - ./pulsar3-standalone.yaml

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=xdbxdb"
    networks:
      - xdb
  postgres:
    image: postgres:12.4
    environment:
      POSTGRES_USER: xdb
      POSTGRES_PASSWORD: xdbxdb
    ports:
      - "5432:5432"
    networks:
      - xdb