version: '3.8'

# Note this is to contain all dependencies to run for integ tests locally
# TODO add Pulsar Debezium Connect for MySQL
include:
  - ./pulsar3-standalone.yaml

services:
  mysql:
    image: debezium/example-mysql:2.4 # this is MySQL8 with sample:https://github.com/debezium/container-images/blob/main/examples/mysql/2.4/Dockerfile
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=xdbxdb"
    networks:
      - xdb
  postgres:
    image: debezium/example-postgress:1.8 # this is postgres14 with sample data(inventory): https://github.com/debezium/container-images/blob/main/examples/postgres/1.8/Dockerfile#L1
    environment:
      POSTGRES_USER: xdb
      POSTGRES_PASSWORD: xdbxdb
    ports:
      - "5432:5432"
    networks:
      - xdb
  pulsar-debezium-postgres-connect:
    image: apachepulsar/pulsar:3.1.0
    entrypoint: bin/pulsar-admin source localrun --source-config-file connectors/debezium-postgres-source-config.yaml
    network_mode: host # use host for now until the issue is resolved https://github.com/apache/pulsar/issues/21276
    volumes:
      - ./connectors:/pulsar/connectors
    depends_on:
      - pulsar-server