version: '3.8'

services:
  mysql:
    image: mysql:8.1
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=xdbxdb"
    networks:
      - xdb
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: xdb
      POSTGRES_PASSWORD: xdbxdb
    ports:
      - "5432:5432"
    networks:
      - xdb
networks:
  xdb:
    driver: bridge