version: '3.8'

services:
  mysql:
    image: mysql:8.1
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=xcherryio"
    networks:
      - xcherry
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: xcherry
      POSTGRES_PASSWORD: xcherryio
    ports:
      - "5432:5432"
    networks:
      - xcherry
networks:
  xcherry:
    driver: bridge