version: '3.8'

# TODO add Pulsar Debezium Connect for MySQL
services:
  mysql:
    image: debezium/example-mysql:2.4 # this is MySQL8 with sample:https://github.com/debezium/container-images/blob/main/examples/mysql/2.4/Dockerfile
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=xdbxdb"
    networks:
      - xdb
  pulsar-server:
    image: apachepulsar/pulsar:3.1.0
    entrypoint: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"
    networks:
      - xdb
    environment:
      - "MYSQL_ROOT_PASSWORD=xdbxdb"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://pulsar-server:8080/metrics/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
networks:
  xdb:
    driver: bridge