version: '3.8'

include:
  - ./pulsar3-standalone.yaml

services:
  mysql:
    image: mysql:8.1
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=xdbxdb"
    networks:
      - xdb