version: '3.8'

# TODO add Pulsar Debezium Connect for MySQL
include:
  - ./pulsar3-standalone.yaml

services:
  mysql:
    image: debezium/example-mysql:2.4 # this is MySQL8 with sample:https://github.com/debezium/container-images/blob/main/examples/mysql/2.4/Dockerfile
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=xdbxdb"
    networks:
      - xdb