version: '3.8'

include:
  - ./pulsar3-standalone.yaml

services:
  postgres:
    image: postgres:12.4
    environment:
      POSTGRES_USER: xdb
      POSTGRES_PASSWORD: xdbxdb
    ports:
      - "5432:5432"
    networks:
      - xdb