version: '3.8'

# from https://pulsar.apache.org/docs/3.1.x/standalone-docker/
# docker run -it -p 6650:6650  -p 8080:8080 --mount source=pulsardata,target=/pulsar/data --mount source=pulsarconf,target=/pulsar/conf apachepulsar/pulsar:3.1.0 bin/pulsar standalone
services:
  pulsar-server:
    image: apachepulsar/pulsar:3.1.0
    entrypoint: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"
    networks:
      - xdb
    environment:
      - "MYSQL_ROOT_PASSWORD=xdbxdb"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://pulsar-server:8080/metrics/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
#    volumes:
#      - ./data:/pulsar/data/zookeeper
#      - ./conf:/pulsar/conf
networks:
  xdb:
    driver: bridge