tenant: "public"
namespace: "default"
name: "debezium-postgres-source"
topicName: "debezium-postgres-topic"
archive: "connectors/pulsar-io-debezium-postgres-3.1.0.nar"
parallelism: 1

configs:
  database.hostname: "postgres"
  database.port: "5432"
  database.user: "xdb"
  database.password: "xdbxdb"
  database.dbname: "postgres"
  database.server.name: "dbserver1"
  schema.whitelist: "inventory"
  #table.whitelist: "inventory"
  pulsar.service.url: "pulsar://pulsar:6650"
  database.history.pulsar.service.url: "pulsar://pulsar:6650"
  
  
