name: All Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  workflow:
    name: Build/Test

    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}

      - name: Checkout Code Base
        uses: actions/checkout@v3

      - name: Make Binaries
        run: make bins

      - name: "Set up all databases + Pulsar environment"
        run: docker compose -f docker-compose/dev/integ-all.yaml up -d

      - name: Install Postgres schema #wait for 5 seconds for env to be ready 
        run: sleep 5 && make install-schema-postgres
        
      - name: Start Postgres server # then run in the background
        run: ./xdb-server --config ./config/development-postgres.yaml & 
        
      - name: Run Tests
        run:  make tests

      - name: Dump docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2
        
      - name: Upload coverage reports to Codecov # TODO merge reports from multiple test commands when MySQL is added
        uses: codecov/codecov-action@v3