name: Postgres14 Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  workflow:
    name: IntegrationTests

    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}

      - name: Checkout Code Base
        uses: actions/checkout@v3

      - name: Make Binaries
        run: make bins
        
      - name: "Set up Postgres Pulsar environment"
        run: docker compose -f docker-compose/dev/postgres14-pulsar.yaml up -d

      - name: Install Postgres schema #wait for 5 seconds for env to be ready 
        run: sleep 5 && make install-schema-postgres
        
      - name: Start Postgres server # then run in the background
        run: ./xdb-server&

      - name: Run Postgres IntegrationTest
        run:  make integTests
        
      - name: Dump docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2