name: Postgres14 Cluster Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  workflow:
    name: IntegrationTests

    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}

      - name: Checkout Code Base
        uses: actions/checkout@v3

      - name: Make Binaries
        run: make bins
        
      - name: "Set up Postgres environment"
        run: docker compose -f docker-compose/dev/postgres14.yaml up -d

      - name: Install Postgres schema #wait for 5 seconds for env to be ready 
        run: sleep 5 && make install-schema-postgres
        
      - name: Start Api server # then run in the background
        run: ./xcherry-server --config ./config/development-postgres-cluster-api.yaml --service api&

      - name: Start Async server 1 # then run in the background
        run: ./xcherry-server --config ./config/development-postgres-cluster-async-1.yaml --service async&

      - name: Start Async server 2 # then run in the background
        run: ./xcherry-server --config ./config/development-postgres-cluster-async-2.yaml --service async&

      - name: Start Async server 3 # then run in the background
        run: ./xcherry-server --config ./config/development-postgres-cluster-async-3.yaml --service async&

      - name: Run Postgres IntegrationTest
        run:  make integTestsWithLocalServer
        
      - name: Dump docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2