name: static check
on: pull_request

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: golangci-lint by reviewdog
        uses: reviewdog/action-golangci-lint@v2
      - name: Check code formatting using gofmt
        uses: Jerome1337/gofmt-action@v1.0.5